# Generated by Django 3.2.16 on 2023-01-17 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import voteit.core.abcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0014_auto_20230112_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='meeting.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(voteit.core.abcs.AuditLogMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='activeuser',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='active_activeuser_unique_per_meeting'),
        ),
    ]
