# Generated by Django 3.2.15 on 2022-09-17 10:53

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisation", "0008_alter_organisationroles_unique_together"),
        ("meeting", "0007_alter_meetingroles_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("on", "On"), ("off", "Off")],
                        default="off",
                        editable=False,
                        max_length=50,
                    ),
                ),
                ("component_name", models.CharField(max_length=30)),
                (
                    "settings_data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="JSON-serialized settings",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="organisation.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation component",
                "verbose_name_plural": "Organisation components",
            },
        ),
        migrations.CreateModel(
            name="MeetingComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("on", "On"), ("off", "Off")],
                        default="off",
                        editable=False,
                        max_length=50,
                    ),
                ),
                ("component_name", models.CharField(max_length=30)),
                (
                    "settings_data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="JSON-serialized settings",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="meeting.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting component",
                "verbose_name_plural": "Meeting components",
            },
        ),
    ]
