# Generated by Django 5.2.13 on 2026-05-11 10:00

import voteit.core.models
import voteit.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=voteit.core.models.user_image_upload_to, validators=[voteit.core.validators.ImageValidator()]),
        ),
    ]
