# Generated by Django 5.2.13 on 2026-04-29 13:19

import voteit.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics', validators=[voteit.core.utils.ContentTypeValidator(('image/webp', 'image/jpeg', 'image/png')), voteit.core.utils.FileSizeValidator(300000)], verbose_name='Profile image'),
        ),
    ]
