# Generated by Django 3.2.7 on 2021-10-22 12:21

from django.conf import settings
import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import voteit.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposal', '0001_initial'),
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electoral_registers', to='meeting.meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', voteit.core.fields.RichTextField(blank=True, default='')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('state', models.CharField(choices=[('private', 'Private'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('finished', 'Finished'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='private', editable=False, max_length=50)),
                ('title', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=200)),
                ('method_name', models.CharField(max_length=20)),
                ('settings_data', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(editable=False, null=True)),
                ('closed', models.DateTimeField(editable=False, null=True)),
                ('ballot_data', models.TextField(editable=False, null=True, verbose_name='JSON-serialized ballot data')),
                ('ballot_checksum', models.CharField(editable=False, max_length=128, null=True, verbose_name='SHA512 checksum of ballot data')),
                ('abstains', models.PositiveIntegerField(default=0, editable=False, verbose_name='Abstentions')),
                ('result_data', models.JSONField(editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='JSON-serialized result data')),
                ('agenda_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='agenda.agendaitem')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_poll_poll', to=settings.AUTH_USER_MODEL)),
                ('electoral_register', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='poll.electoralregister')),
                ('initial_electoral_register', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls_initial', to='poll.electoralregister')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_poll_poll', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='meeting.meeting')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentions_poll_poll', to=settings.AUTH_USER_MODEL)),
                ('proposals', models.ManyToManyField(related_name='polls', to='proposal.Proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoterWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.electoralregister')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('abstain', models.BooleanField(default=False)),
                ('vote_data', models.TextField(blank=True, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poll.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='electoralregister',
            name='voters',
            field=models.ManyToManyField(related_name='electoral_registers', through='poll.VoterWeight', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'poll'), name='poll_vote_unique_vote_for_user'),
        ),
    ]
