# Generated by Django 3.2.7 on 2021-10-30 08:34
from json import loads

from django.db import migrations


def populate_result_vote_count(apps, schema_editor):
    Poll = apps.get_model('poll', 'Poll')
    for poll in Poll.objects.all():
        if poll.ballot_data and poll.result_data:
            try:
                ballots: dict[object, int] = loads(poll.ballot_data)
            except ValueError:     # Don't die if there is incorrect json for some reason.
                continue
            result_data: dict = poll.result_data
            result_data["vote_count"] = sum(ballots.values())
            poll.result_data = result_data
            poll.save()


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_result_vote_count)
    ]
