# Generated by Django 3.2.13 on 2022-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20220418_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='electoralregister',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
