# Generated by Django 3.2.16 on 2022-11-04 10:17

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_electoralregister_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='state',
            field=django_fsm.FSMField(choices=[('private', 'Private'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('finished', 'Finished'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('no_result', 'No result')], default='private', editable=False, max_length=50),
        ),
    ]
