# Generated by Django 3.2.19 on 2023-05-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='p_ord',
            field=models.CharField(choices=[('c', 'Chronological'), ('a', 'Alphabetical'), ('r', 'Random')], default='c', max_length=1, verbose_name='Proposal ordering'),
        ),
    ]
