# Generated by Django 3.2.22 on 2023-10-18 14:29

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_poll_p_ord'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='withheld_result',
            field=models.BooleanField(default=False, verbose_name='Withheld result'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='state',
            field=django_fsm.FSMField(choices=[('private', 'Private'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('finished', 'Finished'), ('withheld', 'Withheld'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('no_result', 'No result')], default='private', editable=False, max_length=50),
        ),
    ]
