# Generated by Django 4.2.15 on 2024-08-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0010_alter_poll_author_alter_poll_last_modified_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="description",
        ),
    ]
