# Generated by Django 5.2.3 on 2025-08-12 15:20

import django.db.models.deletion
import rules.contrib.models
import voteit.core.abcs
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0026_remove_meetinggroup_prevent_delegate_to_self_and_more"),
        ("poll", "0011_remove_poll_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_transfers",
                        to="meeting.meeting",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "meeting"),
                        name="poll_votetransfer_meeting_source",
                    )
                ],
            },
            bases=(
                voteit.core.abcs.AuditLogMixin,
                models.Model,
                rules.contrib.models.RulesModelMixin,
            ),
        ),
    ]
