# Generated by Django 5.2.13 on 2026-05-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_remove_voterweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='last_modified_by',
        ),
    ]
