# Generated by Django 5.2.14 on 2026-06-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_remove_poll_last_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='initial_electoral_register',
        ),
        migrations.AlterField(
            model_name='poll',
            name='state',
            field=models.CharField(choices=[('private', 'Private'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('finished', 'Finished'), ('withheld', 'Withheld'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('no_result', 'No result')], default='private', max_length=20),
        ),
    ]
