[metadata]
name = voteit
version = 0.1
description = VoteIT
long_description = file: README.md
url = https://www.voteit.se/
author = VoteIT dev team
author_email = info@voteit.se
license = GPLv3  # Example license

classifiers =
    Environment :: Web Environment
    Framework :: Django
    Framework :: Django :: 3
    Intended Audience :: Developers
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.8
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content

[options]
install_requires =
    channels>=3.0.0
    channels_redis
    django < 4, >= 3.1.7
    django-cors-headers
    djangorestframework < 4, >= 3.12
    djangorestframework-fsm < 1, >= 0.1.2
    django-model-utils
    django-rest-framework-rules
    django-filter
    django-fsm
    django-fsm-admin
    django-rq >= 2.4.0, <3
    rq >= 1.10.1, < 2
    rq-scheduler
    markdown
    pydantic[email]
    pyyaml
    rules
    STVPoll
    bleach
    beautifulsoup4
    lxml
    python3-vote-core
    requests_oauthlib
    slack-logger


test_suite = tests
include_package_data = true
packages = find:


[options.extras_require]
testing =
    coverage>=5.0
    fakeredis
    responses