# Generated by Django 3.2.7 on 2021-10-22 12:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import voteit.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', voteit.core.fields.RichTextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('state', models.CharField(choices=[('published', 'Published'), ('retracted', 'Retracted'), ('voting', 'Voting'), ('approved', 'Approved'), ('denied', 'Denied'), ('unhandled', 'Unhandled')], default='published', max_length=50)),
                ('prop_id', models.CharField(max_length=50)),
                ('agenda_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='agenda.agendaitem')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_proposal_proposal', to=settings.AUTH_USER_MODEL)),
                ('meeting_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='meeting.meetinggroup')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentions_proposal_proposal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('body', models.TextField(default='')),
                ('base_tag', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_documents', to='agenda.agendaitem')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_documents', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_documents_last_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiffProposal',
            fields=[
                ('proposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proposal.proposal')),
            ],
            options={
                'abstract': False,
            },
            bases=('proposal.proposal',),
        ),
        migrations.CreateModel(
            name='TextParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('paragraph_id', models.PositiveSmallIntegerField(default=1)),
                ('agenda_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_paragraphs', to='agenda.agendaitem')),
                ('text_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_paragraphs', to='proposal.textdocument')),
            ],
        ),
        migrations.AddConstraint(
            model_name='textparagraph',
            constraint=models.UniqueConstraint(fields=('paragraph_id', 'text_document'), name='paragraph_id_unique_for_text'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('prop_id', 'agenda_item'), name='prop_id_unique_for_ai'),
        ),
        migrations.AddField(
            model_name='diffproposal',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='proposal.textparagraph'),
        ),
    ]
