# Generated by Django 3.2.6 on 2021-10-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='state',
            field=models.CharField(choices=[('published', 'Published'), ('retracted', 'Retracted'), ('voting', 'Voting'), ('approved', 'Approved'), ('denied', 'Denied'), ('unhandled', 'Unhandled')], default='published', max_length=50),
        ),
    ]
