# Generated by Django 3.2.6 on 2022-02-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20220126_1115'),
        ('proposal', '0002_alter_proposal_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='meeting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='meeting.meetinggroup'),
        ),
    ]
