# Generated by Django 3.2.12 on 2022-03-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_auto_20220224_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffproposal',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proposals', to='proposal.textparagraph'),
        ),
    ]
