# Generated by Django 3.2.13 on 2022-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_auto_20220418_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocument',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
