# Generated by Django 3.2.16 on 2022-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_alter_textdocument_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocument',
            name='base_tag',
            field=models.CharField(max_length=40),
        ),
    ]
