# Generated by Django 3.2.18 on 2023-04-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0018_meetingdialectproxy'),
        ('proposal', '0009_alter_proposal_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='meeting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='proposals', to='meeting.meetinggroup'),
        ),
    ]
