# Generated by Django 4.2.15 on 2024-08-21 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proposal", "0011_proposal_as_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="last_modified_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_modified_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentions_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
