# Generated by Django 5.2.13 on 2026-05-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0012_alter_proposal_last_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='last_modified_by',
        ),
    ]
