# Generated by Django 5.2.13 on 2026-05-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0013_remove_proposal_last_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdocument',
            name='last_modified_by',
        ),
    ]
