# Generated by Django 5.2.14 on 2026-05-28 07:54

import voteit.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0014_remove_textdocument_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocument',
            name='body',
            field=voteit.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
