# Generated by Django 3.2.7 on 2021-10-22 12:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import voteit.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('title', models.CharField(max_length=100)),
                ('state', django_fsm.FSMField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retracted', 'Retracted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('unhandled', 'Unhandled')], default='draft', max_length=50, protected=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motions', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_motion_motion', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentions_motion_motion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', voteit.core.fields.RichTextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('title', models.CharField(max_length=100)),
                ('state', django_fsm.FSMField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=50, protected=True)),
                ('public', models.BooleanField(default=False, verbose_name='Is anyone allowed to view motions except drafts and retracted?')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_motion_motionprocess', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_motion_motionprocess', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentions_motion_motionprocess', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motion_processes', to='organisation.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotionProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='motion.motion')),
            ],
        ),
        migrations.AddField(
            model_name='motion',
            name='motion_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='motion.motionprocess'),
        ),
        migrations.CreateModel(
            name='MotionProcessRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=tuple, size=None)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='motion.motionprocess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_process_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'context')},
            },
        ),
    ]
