# Generated by Django 5.2.11 on 2026-03-03 09:20

import django.db.models.deletion
import django.utils.timezone
import voteit.core.abcs
import voteit.core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0027_delete_meetingdialectproxy'),
        ('proposal', '0012_alter_proposal_last_modified_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', voteit.core.fields.RichTextField(blank=True, default='')),
                ('intent', models.CharField(blank=True, choices=[('', 'Blank'), ('a', 'Approve'), ('d', 'Deny')], default='', max_length=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('meeting', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='meeting.meeting')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='proposal.proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'constraints': [models.UniqueConstraint(fields=('proposal', 'user'), name='notes_note_unique')],
            },
            bases=(voteit.core.abcs.AuditLogMixin, models.Model),
        ),
    ]
