# Generated by Django 3.2.7 on 2021-10-22 12:21

from django.conf import settings
import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('safe_pos', models.BooleanField(default=False)),
                ('started', models.DateTimeField(null=True)),
                ('seconds', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', editable=False, max_length=50)),
                ('agenda_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_lists', to='agenda.agendaitem')),
                ('current', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speaker.speaker', verbose_name='Current speaker, if any')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeakerListSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('inactive', 'inactive'), ('active', 'Active'), ('archived', 'Archived')], default='inactive', editable=False, max_length=50)),
                ('title', models.CharField(max_length=200, null=True)),
                ('method_name', models.CharField(max_length=20)),
                ('settings_data', models.JSONField(editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='JSON-serialized settings data')),
                ('safe_positions', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2')], null=True, verbose_name='When a list is active, mark the top X positions as safe automatically. Safe speakers will never be moved down.')),
                ('active_list', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_system', to='speaker.speakerlist', verbose_name='Currently active speaker list')),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_systems', to='meeting.meeting', verbose_name='Related meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeakerSystemRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=tuple, size=None)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speaker.speakerlistsystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_speaker_speakersystemroles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speaker system roles',
                'verbose_name_plural': 'Speaker system roles',
            },
        ),
        migrations.AddField(
            model_name='speakerlist',
            name='speaker_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_lists', to='speaker.speakerlistsystem'),
        ),
        migrations.AddField(
            model_name='speakerlist',
            name='speakers',
            field=models.ManyToManyField(related_name='speaker_lists', through='speaker.Speaker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speaker',
            name='speaker_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_items', to='speaker.speakerlist'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
