# Generated by Django 3.2.6 on 2021-11-02 11:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerlistsystem',
            name='meeting_roles_to_speaker',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=tuple, size=None),
        ),
    ]
