# Generated by Django 3.2.15 on 2022-08-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0004_auto_20220418_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerlistsystem',
            name='state',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('archived', 'Archived')], default='inactive', editable=False, max_length=50),
        ),
    ]
