# Generated by Django 3.2.15 on 2022-09-09 11:28
from django.db import migrations, models


def reorder_with_new_data(apps, *args):
    SpeakerList = apps.get_model("speaker", "speakerlist")
    for sl in SpeakerList.objects.all():
        sl.order = ",".join(
            str(x)
            for x in sl.speaker_items.filter(order__isnull=False)
            .order_by("order")
            .values_list("user_id", flat=True)
        )
        sl.save()


class Migration(migrations.Migration):

    dependencies = [
        ("speaker", "0005_alter_speakerlistsystem_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerlist",
            name="order",
            field=models.TextField(
                default="", verbose_name="Order of user PK, comma separated"
            ),
        ),
        migrations.RunPython(
            reorder_with_new_data, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="speaker",
            name="order",
        ),
        migrations.RemoveField(
            model_name="speaker",
            name="safe_pos",
        ),
    ]
