# Generated by Django 3.2.15 on 2022-09-20 12:18

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0006_auto_20220909_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerlistsystem',
            name='state',
            field=django_fsm.FSMField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('archived', 'Archived')], default='active', editable=False, max_length=50),
        ),
    ]
