# Generated by Django 3.2.22 on 2023-10-27 11:21

from django.db import migrations
import voteit.core.fields

_MODEL = ("speaker", "SpeakerSystemRoles")
_MODEL_SLS = ("speaker", "SpeakerListSystem")
_SHORTER_ROLE_NAME_MAP = {
    "participant": "pa",
    "moderator": "mo",
    "potential_voter": "pv",
    "discusser": "di",
    "proposer": "pr",
}


def migrate_role_assigned(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        roles.migration_assigned = roles.assigned
        model.save_base(roles, raw=True)


def reverse_migrate_role_assigned(apps, schema_editor):
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        roles.assigned = roles.migration_assigned
        model.save_base(roles, raw=True)


def migrate_role_sls(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    model = apps.get_model(*_MODEL_SLS)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        values = []
        for v in roles.meeting_roles_to_speaker:
            values.append(_SHORTER_ROLE_NAME_MAP[v])
        roles.migration_meeting_roles_to_speaker = values
        model.save_base(roles, raw=True)


def reverse_migrate_role_sls(apps, schema_editor):
    model = apps.get_model(*_MODEL_SLS)
    db_alias = schema_editor.connection.alias
    reversed_map = {v: k for k, v in _SHORTER_ROLE_NAME_MAP.items()}
    for roles in model.objects.using(db_alias).all():
        values = []
        for v in roles.migration_meeting_roles_to_speaker:
            values.append(reversed_map[v])
        roles.meeting_roles_to_speaker = values
        model.save_base(roles, raw=True)


class Migration(migrations.Migration):
    dependencies = [
        ("speaker", "0008_alter_speaker_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakersystemroles",
            name="migration_assigned",
            field=voteit.core.fields.RolesField(default="", max_length=30),
        ),
        migrations.RunPython(
            code=migrate_role_assigned, reverse_code=reverse_migrate_role_assigned
        ),
        migrations.RemoveField(
            model_name="speakersystemroles",
            name="assigned",
        ),
        migrations.RenameField(
            model_name="speakersystemroles",
            new_name="assigned",
            old_name="migration_assigned",
        ),
        # SpeakerListSystem
        migrations.AddField(
            model_name="speakerlistsystem",
            name="migration_meeting_roles_to_speaker",
            field=voteit.core.fields.RolesField(default="", max_length=60),
        ),
        migrations.RunPython(
            code=migrate_role_sls, reverse_code=reverse_migrate_role_sls
        ),
        migrations.RemoveField(
            model_name="speakerlistsystem",
            name="meeting_roles_to_speaker",
        ),
        migrations.RenameField(
            model_name="speakerlistsystem",
            new_name="meeting_roles_to_speaker",
            old_name="migration_meeting_roles_to_speaker",
        ),
    ]
