# Generated by Django 3.2.22 on 2023-11-02 14:35

from django.db import migrations
import voteit.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("speaker", "0009_speakersystemroles_migration_assigned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerlistsystem",
            name="meeting_roles_to_speaker",
            field=voteit.core.fields.RolesField(
                choices=[
                    ("di", "Discusser"),
                    ("mo", "Moderator"),
                    ("pa", "Participant"),
                    ("pv", "Potential voter"),
                    ("pr", "Proposer"),
                ],
                default="",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="speakersystemroles",
            name="assigned",
            field=voteit.core.fields.RolesField(
                choices=[("list_moderator", "List moderator"), ("speaker", "Speaker")],
                default="",
                max_length=30,
            ),
        ),
    ]
