# Generated by Django 3.2.22 on 2023-11-08 09:14

from django.db import migrations, models
import django.db.models.deletion

_MODEL = ("speaker", "SpeakerListSystem")
_ROOM_MODEL = ("room", "Room")


def migrate_sls_marry_room(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    model = apps.get_model(*_MODEL)
    room_model = apps.get_model(*_ROOM_MODEL)
    db_alias = schema_editor.connection.alias
    for sls in model.objects.using(db_alias).all():
        title = sls.title or sls.meeting.title or str(sls.meeting)
        room = room_model.objects.using(db_alias).create(
            title=title, meeting=sls.meeting
        )
        sls.room = room
        room_model.save_base(sls, raw=True)


def migrate_sls_divorce_room(apps, schema_editor):
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for sls in model.objects.using(db_alias).all():
        sls.title = sls.room.title
        sls.room = None
        model.save_base(sls, raw=True)


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
        ("speaker", "0010_auto_20231102_1535"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerlistsystem",
            name="room",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sls",
                to="room.room",
                verbose_name="Room",
            ),
        ),
        migrations.RunPython(
            code=migrate_sls_marry_room, reverse_code=migrate_sls_divorce_room
        ),
        migrations.RemoveField(
            model_name="speakerlistsystem",
            name="title",
        ),
        migrations.AlterField(
            model_name="speakerlistsystem",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speaker_systems",
                to="meeting.meeting",
                verbose_name="Related meeting",
            ),
        ),
    ]
