# Generated by Django 3.2.22 on 2023-11-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
        ("speaker", "0011_speakerlistsystem_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerlistsystem",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sls",
                to="room.room",
                verbose_name="Room",
            ),
        ),
    ]
