# Generated by Django 3.2.22 on 2024-01-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0012_alter_speakerlistsystem_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerlistsystem',
            name='show_time',
            field=models.BooleanField(default=False, verbose_name='Show time spoken for all'),
        ),
    ]
