# Generated by Django 4.2.15 on 2025-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaker", "0014_alter_speakersystemroles_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="speaker",
            constraint=models.UniqueConstraint(
                models.F("speaker_list"),
                condition=models.Q(
                    ("seconds__isnull", True), ("started__isnull", False)
                ),
                name="only_one_ongoing_speaker",
            ),
        ),
        migrations.AddConstraint(
            model_name="speaker",
            constraint=models.UniqueConstraint(
                models.F("user"),
                models.F("speaker_list"),
                condition=models.Q(("seconds__isnull", True)),
                name="only_unique_users_in_queue",
            ),
        ),
    ]
