# Generated by Django 4.2.22 on 2025-06-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("speaker", "0015_speaker_only_one_ongoing_speaker_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speakerlist",
            name="current",
        ),
    ]
