# Generated by Django 5.2.3 on 2025-06-16 14:42

import django.db.models.deletion
from django.db import migrations, models


def populate_cached_fields(apps, *args):
    SpeakerList = apps.get_model("speaker", "speakerlist")
    for sl in SpeakerList.objects.all().select_related("speaker_system"):
        sl.meeting_id = sl.speaker_system.meeting_id
        sl.room_id = sl.speaker_system.room_id
        sl.save_base(raw=True)  # Avoid triggering as much as possible


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0026_remove_meetinggroup_prevent_delegate_to_self_and_more"),
        ("speaker", "0016_remove_speakerlist_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerlist",
            name="meeting",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="meeting.meeting",
            ),
        ),
        migrations.AddField(
            model_name="speakerlist",
            name="room",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="room.room",
            ),
        ),
        migrations.RunPython(populate_cached_fields),
        # And remove nullable
        migrations.AlterField(
            model_name="speakerlist",
            name="meeting",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="meeting.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="speakerlist",
            name="room",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="room.room",
            ),
        ),
    ]
