# Generated by Django 3.2.7 on 2021-10-22 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_policy', '0001_initial'),
        ('meeting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorapprovedaccess',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_policy_moderatorapprovedaccess', to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='meetinginvite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetinginvite',
            name='last_modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetinginvite',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='meetinginvite',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitedispatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitedispatch',
            name='invites',
            field=models.ManyToManyField(to='access_policy.MeetingInvite'),
        ),
        migrations.AddField(
            model_name='invitedispatch',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_dispatches', to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='automaticaccess',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_policy_automaticaccess', to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='access_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='access_policy.moderatorapprovedaccess'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
