# Generated by Django 3.2.6 on 2022-01-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_policy', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinginvite',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meetinginvite',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='meetinginvite',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meetinginvite',
            name='used_by',
        ),
        migrations.DeleteModel(
            name='InviteDispatch',
        ),
        migrations.DeleteModel(
            name='MeetingInvite',
        ),
    ]
