# Generated by Django 3.2.12 on 2022-02-24 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access_policy', '0003_auto_20220110_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
