# Generated by Django 3.2.13 on 2022-04-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_policy', '0004_alter_accessrequest_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='automaticaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moderatorapprovedaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
