# Generated by Django 3.2.22 on 2023-11-02 14:35

from django.db import migrations
import voteit.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('access_policy', '0007_auto_20231101_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticaccess',
            name='roles_given',
            field=voteit.core.fields.RolesField(choices=[('di', 'Discusser'), ('mo', 'Moderator'), ('pa', 'Participant'), ('pv', 'Potential voter'), ('pr', 'Proposer')], default='', max_length=60),
        ),
    ]
