# Generated by Django 4.2.15 on 2024-08-21 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "meeting",
            "0025_alter_meeting_author_alter_meeting_last_modified_by_and_more",
        ),
        ("access_policy", "0008_alter_automaticaccess_roles_given"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automaticaccess",
            name="meeting",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="meeting.meeting",
            ),
        ),
    ]
