from __future__ import annotations

from datetime import datetime
from logging import getLogger
from random import sample
from string import ascii_lowercase
from typing import TYPE_CHECKING

from auditlog.registry import auditlog
from django.conf import settings
from django.db import models, transaction
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django_fsm import FSMField, transition
from model_utils.managers import InheritanceManager
from rules.contrib.models import RulesModelMixin

from voteit.core import PERM
from voteit.core.abcs import AgendaItemContext, MeetingContext
from voteit.core.fields import RichTextField
from voteit.core.models import BaseContent
from voteit.core.utils import strip_html
from voteit.proposal import PERM_RETRACT
from voteit.proposal.workflows import ProposalWf
from voteit.reactions.mixins import Reactable
from voteit.stats.registry import history_log

if TYPE_CHECKING:
    from voteit.agenda.models import AgendaItem
    from voteit.core.models import User
    from voteit.meeting.models import Meeting, MeetingGroup

__all__ = (
    "Proposal",
    "DiffProposal",
    "TextDocument",
    "TextParagraph",
)

logger = getLogger(__name__)

_PROP_LOG_FIELDS = [
    "state",
    "author",
    "meeting_group",
    "prop_id",
    "agenda_item",
    "as_group",
    "body",
    "tags",
]


@history_log("agenda_item__meeting__organisation")
@auditlog.register(
    include_fields=_PROP_LOG_FIELDS,
)
class Proposal(BaseContent, AgendaItemContext, MeetingContext, Reactable):
    """
    A motion or amendment submitted by a participant within an agenda item.

    Lifecycle (``ProposalWf``): ``published → retracted / voting → approved / denied / unhandled``.
    The ``prop_id`` is a unique, human-readable identifier within the agenda item (e.g. ``"jane-1"``),
    generated by the meeting's proposal-ID policy on first save and automatically added to ``tags``.

    ``DiffProposal`` (MTI subclass) extends this for amendments against a ``TextParagraph``.
    Use ``objects.select_subclasses()`` (``InheritanceManager``) when you need concrete types.

    A proposal can be submitted on behalf of a ``MeetingGroup`` (``as_group=True``). This is
    cleared automatically if the ``meeting_group`` FK is absent.
    """

    name = "proposal"
    state: str = FSMField(default=ProposalWf.initial, choices=ProposalWf.choices())
    author: User = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.RESTRICT,
        blank=True,
        null=True,
        related_name="proposals",
    )
    meeting_group: MeetingGroup = models.ForeignKey(
        "meeting.MeetingGroup",
        on_delete=models.RESTRICT,
        null=True,
        blank=True,
        related_name="proposals",
    )
    prop_id: str = models.CharField(max_length=50)
    agenda_item: AgendaItem = models.ForeignKey(
        "agenda.AgendaItem",
        on_delete=models.CASCADE,
        null=True,
        related_name="proposals",
    )
    as_group: bool = models.BooleanField(
        verbose_name="Posted as group rather than author", default=False
    )

    @property
    def meeting(self) -> Meeting | None:
        """While not directly related, it's still good to be able to do lookups this way"""
        if self.agenda_item:
            return self.agenda_item.meeting

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["prop_id", "agenda_item"],
                name="prop_id_unique_for_ai",
            )
        ]

    @transition(
        field=state,
        source=ProposalWf.PUBLISHED,
        target=ProposalWf.RETRACTED,
        permission=f"proposal.{PERM_RETRACT}_proposal",
        custom={"title": _("Retract")},
    )
    def retract(self):
        """Normal user operation to retract. Or for moderators."""
        pass

    @transition(
        field=state,
        source=[ProposalWf.PUBLISHED, ProposalWf.RETRACTED],
        target=ProposalWf.VOTING,
        permission=f"proposal.{PERM.CHANGE}_proposal",
        custom={"title": _("Lock for vote")},
    )
    def lock_for_vote(self):
        """When a vote starts, mark all proposals as "voting" so they can't be retracted.
        In case a retracted proposal is part of the vote, lock that too
        since it might have been retracted very late.
        """
        pass

    @transition(
        field=state,
        source=[ProposalWf.PUBLISHED, ProposalWf.VOTING, ProposalWf.DENIED],
        target=ProposalWf.APPROVED,
        permission=f"proposal.{PERM.CHANGE}_proposal",
        custom={"title": _("Approve")},
    )
    def approved(self):
        """Proposal approved via poll or moderator."""
        pass

    @transition(
        field=state,
        source=[ProposalWf.PUBLISHED, ProposalWf.VOTING, ProposalWf.APPROVED],
        target=ProposalWf.DENIED,
        permission=f"proposal.{PERM.CHANGE}_proposal",
        custom={"title": _("Deny")},
    )
    def denied(self):
        """Proposal denied via poll or moderator."""
        pass

    @transition(
        field=state,
        source=ProposalWf.PUBLISHED,
        target=ProposalWf.UNHANDLED,
        permission=f"proposal.{PERM.CHANGE}_proposal",
        custom={"title": _("Mark as unhandled")},
    )
    def unhandled(self):
        """Proposal was never handled. Automatic transition or from moderator."""
        pass

    @transition(
        field=state,
        source="+",
        target=ProposalWf.PUBLISHED,
        permission=f"proposal.{PERM.CHANGE}_proposal",
        custom={"title": _("Publish")},
    )
    def publish(self):
        """Reset proposal back to published."""
        pass

    def save(self, **kw):
        if not self.prop_id and self.meeting is not None:
            pid_policy = self.meeting.pid_policy
            suggestion = pid_policy(self)
            if suggestion:
                self.prop_id = suggestion
            else:
                self.prop_id = _new_proposal_id(self)
        if self.prop_id not in self.tags:
            self.tags.append(self.prop_id)
        if self.as_group and not self.meeting_group_id:
            self.as_group = False
        super().save(**kw)

    def __repr__(self):
        return f"<{self.__class__.__name__}: {self}>"

    def __str__(self):
        return f"P:{self.prop_id}"

    objects = InheritanceManager()
    meeting_group_id: None | int
    agenda_item_id: None | int
    author_id: None | int


@auditlog.register(
    include_fields=[
        "title",
        "body",
        "base_tag",
        "agenda_item",
    ],
)
class TextDocument(RulesModelMixin, AgendaItemContext, MeetingContext):
    """
    The full text that's the basis for diff proposals.
    """

    name = "text_document"
    _should_refresh: bool = False
    _original_body: str
    title: str = models.CharField(max_length=100, default="")
    body: str = RichTextField(blank=True, default="", html_cleaner=strip_html)
    base_tag: str = models.CharField(max_length=40)
    created: datetime = models.DateTimeField(editable=False, default=now)
    modified: datetime = models.DateTimeField(editable=False, auto_now=True)
    author: User = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        editable=False,
        null=True,
        related_name="text_documents",
    )
    agenda_item: AgendaItem = models.ForeignKey(
        "agenda.AgendaItem",
        on_delete=models.CASCADE,
        related_name="text_documents",
        null=True,  # Normally no, forced in serializer
    )

    @property
    def meeting(self) -> Meeting | None:
        if self.agenda_item:
            return self.agenda_item.meeting

    @classmethod
    def from_db(cls, db, field_names, values):
        instance = super().from_db(db, field_names, values)
        instance._original_body = instance.body
        return instance

    def create_text_paragraphs(self):
        paragraphs = get_paragraphs(self.body)
        TextParagraph.objects.bulk_create(
            [
                TextParagraph(
                    body=para,
                    text_document=self,
                    agenda_item=self.agenda_item,
                    paragraph_id=i,
                )
                for i, para in enumerate(paragraphs, start=1)
            ]
        )
        self._should_refresh = False

    @property
    def should_refresh(self):
        return self._should_refresh

    def save(self, **kw):
        if self.pk is None:
            self._should_refresh = True
        elif getattr(self, "_original_body", None) != self.body:
            self._should_refresh = True
        # We want all the subsequent creates that comes from the save signal to be within
        # the same transaction. Empty TextDocuments won't make anyone happy.
        with transaction.atomic():
            super().save(**kw)
        self._original_body = self.body

    # Annotations
    objects: models.Manager
    text_paragraphs: models.QuerySet

    def __str__(self):
        return self.title and self.title or f"TextDoc({self.pk})"

    def __repr__(self):
        return f"TextDocument({self.pk}) {self.title[:50]}"


def get_paragraphs(text: str) -> list[str]:
    """
    Split text into paragraphs. Two linebreaks means new.
    """
    output = []
    new_para = True
    for row in text.splitlines():
        row = row.strip()
        if row:
            if new_para:
                output.append(row)
            else:
                output[-1] += "\n"
                output[-1] += row
            new_para = False
        else:
            new_para = True
    return output


class TextParagraph(AgendaItemContext, MeetingContext):
    """
    Text paragraphs are the basis for diff-text functionality.
    These are the initial text body other proposals diff against.
    """

    name = "text_paragraph"
    body: str = models.TextField(editable=False)
    created: datetime = models.DateTimeField(editable=False, default=now)
    modified: datetime = models.DateTimeField(editable=False, auto_now=True)
    paragraph_id: int = models.PositiveSmallIntegerField(default=1)
    text_document: TextDocument = models.ForeignKey(
        "TextDocument",
        on_delete=models.CASCADE,
        related_name="text_paragraphs",
    )
    agenda_item: AgendaItem = models.ForeignKey(
        "agenda.AgendaItem",
        on_delete=models.CASCADE,
        related_name="text_paragraphs",
        null=True,  # Normally no, forced in serializer
    )

    @property
    def tag(self):
        return f"{self.text_document.base_tag}-{self.paragraph_id}"

    @property
    def meeting(self) -> Meeting | None:
        """While not directly related, it still good to be able to do lookups this way"""
        if self.agenda_item:
            return self.agenda_item.meeting

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["paragraph_id", "text_document"],
                name="paragraph_id_unique_for_text",
            )
        ]

    def save(self, **kw):
        """
        Set paragraph_id when initially saving if it isn't set
        """
        if not self.pk and not self.paragraph_id:
            max_val = self.agenda_item.text_paragraphs.aggregate(
                max_val=models.Max("paragraph_id")
            )["max_val"]
            if max_val is not None:
                self.paragraph_id = max_val + 1
        super().save(**kw)

    # Annotations
    objects: models.Manager
    proposals: models.QuerySet


@auditlog.register(
    include_fields=_PROP_LOG_FIELDS
    + [
        "paragraph",
    ],
)
class DiffProposal(Proposal):
    """
    A word-level amendment to a specific paragraph of a ``TextDocument``.

    Extends ``Proposal`` via Django multi-table inheritance. The ``paragraph`` FK
    points to the ``TextParagraph`` being amended; the diff is computed on the fly
    in ``diff.Changes`` for display. A ``TextDocument`` cannot be edited or deleted
    while it has DiffProposals attached (enforced by the ``has_no_proposals`` predicate).
    """

    name = "diff_proposal"
    paragraph: TextParagraph = models.ForeignKey(
        TextParagraph, on_delete=models.RESTRICT, related_name="proposals"
    )

    def save(self, **kw):
        """
        Force paragraph tag
        """
        if self.paragraph.tag not in self.tags:
            self.tags.append(self.paragraph.tag)
        super().save(**kw)


def _new_proposal_id(proposal: Proposal) -> str:
    # FIXME: Do something nice here that isn't just random
    return "".join(sample(ascii_lowercase, 8))
