# Generated by Django 3.2.7 on 2021-10-22 12:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import voteit.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', voteit.core.fields.RichTextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('agenda_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='agenda.agendaitem')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discussions', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_discussion_discussionpost', to=settings.AUTH_USER_MODEL)),
                ('meeting_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discussions', to='meeting.meetinggroup')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentions_discussion_discussionpost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
