# Generated by Django 3.2.12 on 2022-03-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20220224_1410'),
        ('discussion', '0002_alter_discussionpost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionpost',
            name='meeting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discussions', to='meeting.meetinggroup'),
        ),
    ]
