# Generated by Django 3.2.16 on 2023-03-09 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0004_alter_discussionpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
