# Generated by Django 3.2.22 on 2024-02-22 15:00

from django.db import migrations, models


def migrate_as_group(apps, schema_editor):
    model = apps.get_model("discussion", "DiscussionPost")
    db_alias = schema_editor.connection.alias
    no_group_qs = model.objects.using(db_alias).filter(meeting_group__isnull=True)
    no_group_qs.update(as_group=False)
    with_group_qs = model.objects.using(db_alias).filter(meeting_group__isnull=False)
    with_group_qs.update(as_group=True)


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0005_alter_discussionpost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionpost",
            name="as_group",
            field=models.BooleanField(
                default=False, verbose_name="Posted as group rather than author"
            ),
        ),
        migrations.RunPython(
            code=migrate_as_group, reverse_code=migrations.RunPython.noop
        ),
    ]
