# Generated by Django 3.2.7 on 2021-10-22 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PNSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pn_system', to='meeting.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='participant_number.pnsystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='participantnumber',
            constraint=models.UniqueConstraint(fields=('user', 'pns'), name='participant_number_participantnumber_unique_check_for_user'),
        ),
        migrations.AddConstraint(
            model_name='participantnumber',
            constraint=models.UniqueConstraint(fields=('pns', 'number'), name='participant_number_participantnumber_unique_check_for_number'),
        ),
    ]
