# Generated by Django 3.2.6 on 2021-11-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_number', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantnumber',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
