# Generated by Django 3.2.12 on 2022-02-24 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('participant_number', '0002_alter_participantnumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantnumber',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
