# Generated by Django 3.2.6 on 2021-11-01 20:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencecheck',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
