# Generated by Django 3.2.12 on 2022-02-24 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_alter_presencecheck_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='presencecheck',
            name='opened',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
