# Generated by Django 3.2.18 on 2023-03-15 09:48
# Manual fixes for moving to component

from django.db import migrations


def move_to_component(apps, schema_editor):
    PresenceSystem = apps.get_model("presence", "PresenceSystem")
    MeetingComponent = apps.get_model("components", "MeetingComponent")
    MeetingComponent.objects.bulk_create(
        [
            MeetingComponent(
                component_name="presence_check", meeting=ps.meeting, state="on"
            )
            for ps in PresenceSystem.objects.all().prefetch_related("meeting")
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0005_alter_presence_user"),
    ]

    operations = [
        migrations.RunPython(move_to_component, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="PresenceSystem",
        ),
    ]
