# Generated by Django 5.2.14 on 2026-06-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0006_delete_presencesystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencecheck',
            name='state',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
