# Generated by Django 3.2.22 on 2023-10-17 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import voteit.core.abcs
import voteit.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speaker', '0008_alter_speaker_user'),
        ('proposal', '0010_alter_proposal_meeting_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0019_auto_20230427_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active?')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Title')),
                ('body', voteit.core.fields.RichTextField(blank=True, default='', verbose_name='Body')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('send_sls', models.BooleanField(default=False, verbose_name='Send Speaker lists?')),
                ('send_proposals', models.BooleanField(default=False, verbose_name='Send proposals?')),
                ('show_time', models.BooleanField(default=False, verbose_name='Show time?')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Who's in the drivers seat?")),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='meeting.meeting')),
                ('sls', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='speaker.speakerlistsystem', verbose_name='Speaker list system')),
            ],
            bases=(voteit.core.abcs.AuditLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HighlightProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlighted_in', to='proposal.proposal')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlighted_proposals', to='room.room')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('sls__isnull', False)), fields=('meeting', 'sls'), name='unique_room_meeting_sls'),
        ),
        migrations.AddConstraint(
            model_name='highlightproposal',
            constraint=models.UniqueConstraint(fields=('room', 'proposal'), name='unique_room_prop'),
        ),
    ]
