# Generated by Django 3.2.22 on 2023-11-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import voteit.core.abcs
import voteit.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("proposal", "0010_alter_proposal_meeting_group"),
        ("meeting", "0021_auto_20231102_1535"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agenda", "0005_lastread_unique_last_read_combination"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open",
                    models.BooleanField(
                        default=False, verbose_name="Is it open for participants?"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "body",
                    voteit.core.fields.RichTextField(
                        blank=True, default="", verbose_name="Body"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "send_sls",
                    models.BooleanField(
                        default=False, verbose_name="Send Speaker lists?"
                    ),
                ),
                (
                    "send_proposals",
                    models.BooleanField(default=False, verbose_name="Send proposals?"),
                ),
                (
                    "show_time",
                    models.BooleanField(default=False, verbose_name="Show time?"),
                ),
                (
                    "agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agenda.agendaitem",
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Who's in the drivers seat?",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="meeting.meeting",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="poll.poll",
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            bases=(voteit.core.abcs.AuditLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HighlightProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlighted_in",
                        to="proposal.proposal",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlighted_proposals",
                        to="room.room",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="highlightproposal",
            constraint=models.UniqueConstraint(
                fields=("room", "proposal"), name="unique_room_prop"
            ),
        ),
    ]
