# Generated by Django 3.2.22 on 2023-12-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='show_ballot',
            field=models.BooleanField(default=False, verbose_name='Show the ballot'),
        ),
    ]
