# Generated by Django 3.2.7 on 2021-10-22 12:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import voteit.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('body', voteit.core.fields.RichTextField(blank=True, default='')),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('private', 'Private'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('archived', 'Archived')], default='private', editable=False, max_length=50)),
                ('block_discussion', models.BooleanField(default=False, verbose_name='Block new discussion posts')),
                ('block_proposals', models.BooleanField(default=False, verbose_name='Block new proposals')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('related_modified', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('meeting', 'order'),
            },
        ),
        migrations.CreateModel(
            name='LastRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_read_set', to='agenda.agendaitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
