# Generated by Django 3.2.15 on 2022-09-23 06:15

from django.db import migrations, models


def duplicate_cleanup(apps, schema_editor):
    LastRead = apps.get_model("agenda", "LastRead")
    duplicate_set = (
        LastRead.objects.values("meeting", "agenda_item", "user")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    for values in duplicate_set:
        values.pop("count")  # Remove count to use as filter
        iterator = iter(LastRead.objects.filter(**values).order_by("-timestamp"))
        next(iterator)  # Skip latest LastRead
        for deletable in iterator:
            deletable.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0004_auto_20220418_0932"),
    ]

    operations = [
        migrations.RunPython(
            duplicate_cleanup,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="lastread",
            constraint=models.UniqueConstraint(
                fields=("agenda_item", "meeting", "user"),
                name="unique_last_read_combination",
            ),
        ),
    ]
