# Generated by Django 5.2.13 on 2026-05-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_agendaitem_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaitem',
            name='last_modified_by',
        ),
    ]
