# Generated by Django 5.2.14 on 2026-06-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_agendaitem_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='state',
            field=models.CharField(choices=[('private', 'Private'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('archived', 'Archived')], default='private', max_length=20),
        ),
    ]
