# Generated by Django 3.2.6 on 2022-01-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='subdomain',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Subdomain name, only the text part without dots'),
        ),
    ]
