# Generated by Django 3.2.6 on 2022-01-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_organisation_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='subdomain',
        ),
        migrations.AddField(
            model_name='organisation',
            name='host',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Host name part'),
        ),
    ]
