# Generated by Django 3.2.6 on 2022-01-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20220123_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth2provider',
            name='auth_url',
        ),
        migrations.RemoveField(
            model_name='oauth2provider',
            name='identity_url',
        ),
        migrations.RemoveField(
            model_name='oauth2provider',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='oauth2provider',
            name='token_url',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='host',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name="Host name part, excluding ports. For instance: 'meeting.voteit.se'"),
        ),
    ]
