# Generated by Django 3.2.15 on 2022-09-06 13:20

from django.db import migrations, models


def populate_empty_page_titles(apps, *args):
    Organisation = apps.get_model("organisation", "Organisation")
    for obj in Organisation.objects.all():
        if not obj.page_title:
            obj.page_title = obj.title
            obj.save(update_fields=["page_title"])


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0006_auto_20220418_0932"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauth2provider",
            name="title",
        ),
        migrations.AddField(
            model_name="organisation",
            name="page_title",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Intro page title"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="title",
            field=models.CharField(
                max_length=100, verbose_name="Title of the organisation itself"
            ),
        ),
        migrations.RunPython(
            populate_empty_page_titles, reverse_code=migrations.RunPython.noop
        ),
    ]
