# Generated by Django 3.2.19 on 2023-05-25 13:26

from django.db import migrations, models
import voteit.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0008_alter_organisationroles_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="active",
            field=models.BooleanField(
                default=True,
                verbose_name="Is this organisation active? Disables login if not.",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="help_info",
            field=voteit.core.fields.RichTextField(
                blank=True, default="", verbose_name="Where to get help for users"
            ),
        ),
    ]
