# Generated by Django 3.2.22 on 2023-10-26 15:09

from django.db import migrations
import voteit.core.fields

_MODEL = ("organisation", "OrganisationRoles")


def migrate_role(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        roles.migration_assigned = roles.assigned
        roles.save()


def reverse_migrate_role(apps, schema_editor):
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        roles.assigned = roles.migration_assigned
        roles.save()


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0009_auto_20230525_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationroles",
            name="migration_assigned",
            field=voteit.core.fields.RolesField(default="", max_length=30),
        ),
        migrations.RunPython(code=migrate_role, reverse_code=reverse_migrate_role),
        migrations.RemoveField(
            model_name="organisationroles",
            name="assigned",
        ),
        migrations.RenameField(
            model_name="organisationroles",
            new_name="assigned",
            old_name="migration_assigned",
        ),
    ]
