# Generated by Django 3.2.22 on 2023-10-26 15:09

from django.db import migrations
import voteit.core.fields

_ROLE_LETTER_MIGRATION = (("c", "meeting_creator"), ("m", "org_manager"))
_MODEL = ("organisation", "OrganisationRoles")


def migrate_role_letters(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        # v = ""
        # for letter, name in _ROLE_LETTER_MIGRATION:
        #    if name in roles.assigned:
        #        v += letter
        # roles.migration_assigned = v
        roles.migration_assigned = roles.assigned
        roles.save()


def reverse_migrate_role_letters(apps, schema_editor):
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        # v = []
        # for letter, name in _ROLE_LETTER_MIGRATION:
        #     if letter in roles.migration_assigned:
        #         v.append(name)
        # roles.assigned = v
        roles.assigned = roles.migration_assigned
        roles.save()


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0009_auto_20230525_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationroles",
            name="migration_assigned",
            field=voteit.core.fields.RolesField(default="", max_length=30),
        ),
        migrations.RunPython(
            code=migrate_role_letters, reverse_code=reverse_migrate_role_letters
        ),
        migrations.RemoveField(
            model_name="organisationroles",
            name="assigned",
        ),
        migrations.RenameField(
            model_name="organisationroles",
            new_name="assigned",
            old_name="migration_assigned",
        ),
    ]
