# Generated by Django 3.2.22 on 2023-11-02 14:35

from django.db import migrations
import voteit.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_organisationroles_migration_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationroles',
            name='assigned',
            field=voteit.core.fields.RolesField(choices=[('org_manager', 'Organisation manager'), ('meeting_creator', 'Meeting creator')], default='', max_length=30),
        ),
    ]
