# Generated by Django 5.2.7 on 2025-10-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_alter_organisation_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth2provider',
            name='provider_id',
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
