# Generated by Django 5.2.13 on 2026-05-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_remove_oauth2provider_provider_id_delete_accesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='last_modified_by',
        ),
    ]
