# Generated by Django 5.2.17 on 2026-09-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_oauth2provider_per_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2provider',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Not offered as a login option, but still usable.', verbose_name='Hidden'),
        ),
        migrations.AddField(
            model_name='oauth2provider',
            name='primary',
            field=models.BooleanField(default=False, help_text='Listed before the others.', verbose_name='Primary login'),
        ),
    ]
