# Generated by Django 5.2.17 on 2026-09-28 13:49

import django.db.models.deletion
import django.utils.timezone
import voteit.core.abcs
import voteit.core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0017_remove_userconsent_tos_remove_userconsent_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', voteit.core.fields.RichTextField(blank=True, default='')),
                ('version', models.DateTimeField(default=django.utils.timezone.now, unique=True, verbose_name='Version')),
                ('required_from', models.DateField(blank=True, default=None, null=True, verbose_name='Required from')),
                ('notes', voteit.core.fields.RichTextField(blank=True, default='', verbose_name='Why has this changed?')),
            ],
            options={
                'verbose_name': 'Global terms of service',
                'verbose_name_plural': 'Global terms of service',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='UserAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tos_accepts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Accepts',
                'verbose_name_plural': 'User Accepts',
                'ordering': ['-accepted'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', voteit.core.fields.RichTextField(blank=True, default='')),
                ('version', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos', to='organisation.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Terms Of Service',
                'verbose_name_plural': 'Terms Of Service',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'version'), name='unique org tos version')],
            },
            bases=(voteit.core.abcs.AuditLogMixin, models.Model),
        ),
    ]
