# Generated by Django 5.2.17 on 2026-10-06 13:06

import voteit.core.validators
import voteit.organisation.models
import voteit.organisation.schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0018_globaltermsofservice_useraccept_termsofservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='colors',
            field=models.JSONField(blank=True, default=dict, validators=[voteit.organisation.schemas.validate_colors]),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=voteit.organisation.models.organisation_logo_upload_to, validators=[voteit.core.validators.SVGValidator()]),
        ),
    ]
