# Generated by Django 3.2.7 on 2021-10-22 12:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import voteit.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('title', models.CharField(max_length=100)),
                ('body', voteit.core.fields.RichTextField(blank=True, default='')),
                ('state', django_fsm.FSMField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('archiving', 'Archiving'), ('archived', 'Archived')], default='upcoming', editable=False, max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='When the meeting starts/started.')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='When the meeting ends/ended.')),
                ('public', models.BooleanField(default=False, verbose_name='Is this meeting viewable by anyone?')),
                ('er_policy_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID of used electoral policy')),
                ('proposal_id_policy_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Proposal ID policy name, defaults to system standard')),
                ('archive_after', models.DateTimeField(editable=False, null=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_meeting_meeting', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_meeting_meeting', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentions_meeting_meeting', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='organisation.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=tuple, size=None)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='meeting.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting roles',
                'verbose_name_plural': 'Meeting roles',
            },
        ),
        migrations.CreateModel(
            name='MeetingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', voteit.core.fields.RichTextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_meeting_meetinggroup', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_meeting_meetinggroup', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='meeting.meeting')),
                ('members', models.ManyToManyField(blank=True, related_name='meeting_groups', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentions_meeting_meetinggroup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(through='meeting.MeetingRoles', to=settings.AUTH_USER_MODEL),
        ),
    ]
