# Generated by Django 3.2.7 on 2022-01-26 11:15

from django.db import migrations, models


def set_groupids(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    MeetingGroup = apps.get_model("meeting", "MeetingGroup")
    db_alias = schema_editor.connection.alias
    # .save will automatically set groupid
    for grp in MeetingGroup.objects.using(db_alias).all():
        grp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinggroup',
            name='groupid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='meetinggroup',
            constraint=models.UniqueConstraint(fields=('groupid', 'meeting'), name='unique_meeting_id'),
        ),
        migrations.RunPython(
            set_groupids,
            migrations.RunPython.noop
        ),
    ]
