# Generated by Django 3.2.15 on 2022-08-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20220418_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='public',
            new_name='visible_in_lists',
        ),
    ]
