# Generated by Django 3.2.15 on 2022-08-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_rename_public_meeting_visible_in_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Is this meeting viewable by anyone?'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='visible_in_lists',
            field=models.BooleanField(default=False, verbose_name='Show basic meeting details in lists?'),
        ),
    ]
