# Generated by Django 3.2.15 on 2022-09-14 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0006_auto_20220831_0904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingroles',
            unique_together={('user', 'context')},
        ),
    ]
