# Generated by Django 3.2.15 on 2022-09-14 21:06

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_alter_meetingroles_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('on', 'On'), ('off', 'Off')], default='off', editable=False, max_length=50)),
                ('component_name', models.CharField(max_length=30)),
                ('settings_data', models.JSONField(editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='JSON-serialized settings')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='meeting.meeting')),
            ],
            options={
                'verbose_name': 'Meeting component',
                'verbose_name_plural': 'Meeting components',
            },
        ),
    ]
