# Generated by Django 3.2.16 on 2022-12-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_alter_meetingroles_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='delete_requested',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='pre_delete_state',
            field=models.CharField(editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='state',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('archiving', 'Archiving'), ('archived', 'Archived'), ('deleting', 'Deleting')], default='upcoming', editable=False, max_length=50),
        ),
    ]
