# Generated by Django 3.2.16 on 2022-12-22 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meeting", "0008_auto_20221201_1116"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from GroupMembership._meta.db_table.
                migrations.RunSQL(
                    sql="ALTER TABLE meeting_meetinggroup_members RENAME TO meeting_groupmembership",
                    reverse_sql="ALTER TABLE meeting_groupmembership RENAME TO meeting_meetinggroup_members",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="GroupMembership",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "meetinggroup",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="role_assignments",
                                to="meeting.meetinggroup",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="+",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="meetinggroup",
                    name="members",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="meeting_groups",
                        through="meeting.GroupMembership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
