# Generated by Django 3.2.16 on 2022-12-22 12:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import voteit.core.abcs


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0009_auto_20221222_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembership',
            old_name='meetinggroup',
            new_name='meeting_group',
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('can_propose_as', models.BooleanField(default=False, verbose_name='Can propose as group')),
                ('can_discuss_as', models.BooleanField(default=False, verbose_name='Can discuss as group')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to='meeting.meeting')),
                ('users', models.ManyToManyField(blank=True, related_name='assigned_group_roles', through='meeting.GroupMembership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group role',
                'verbose_name_plural': 'Group roles',
                'ordering': ['title'],
            },
            bases=(voteit.core.abcs.AuditLogMixin, models.Model),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meeting.grouprole'),
        ),
        migrations.AddConstraint(
            model_name='grouprole',
            constraint=models.UniqueConstraint(fields=('title', 'meeting'), name='unique_meeting_grp_title'),
        ),
    ]
