# Generated by Django 3.2.16 on 2023-01-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_auto_20221222_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='group_roles_active',
            field=models.BooleanField(default=False, verbose_name='System for dynamic roles within groups'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='group_votes_active',
            field=models.BooleanField(default=False, verbose_name='Voting power comes from groups rather than individuals'),
        ),
        migrations.AddField(
            model_name='meetinggroup',
            name='votes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
