# Generated by Django 3.2.16 on 2023-01-03 10:16

from django.db import migrations, models
import voteit.meeting.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_auto_20221222_1353'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grouprole',
            name='unique_meeting_grp_title',
        ),
        migrations.AddField(
            model_name='grouprole',
            name='role_id',
            field=models.CharField(default=voteit.meeting.models._rnd_role_id, max_length=100, verbose_name='Role ID, mostly for scripting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='group_roles_active',
            field=models.BooleanField(default=False, verbose_name='System for dynamic roles within groups'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='group_votes_active',
            field=models.BooleanField(default=False, verbose_name='Voting power comes from groups rather than individuals'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='installed_dialects',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Configuration steps for roles, groups etc. that have been run. Comma-separated, in order of installation.'),
        ),
        migrations.AddField(
            model_name='meetinggroup',
            name='votes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AddConstraint(
            model_name='grouprole',
            constraint=models.UniqueConstraint(fields=('title', 'meeting'), name='unique_role_title_for_meeting'),
        ),
        migrations.AddConstraint(
            model_name='grouprole',
            constraint=models.UniqueConstraint(fields=('role_id', 'meeting'), name='unique_role_id_for_meeting'),
        ),
    ]
