# Generated by Django 3.2.16 on 2023-01-04 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_auto_20230103_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprole',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=tuple, size=None),
        ),
    ]
