# Generated by Django 3.2.16 on 2023-01-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_alter_grouprole_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='meeting_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='meeting.meetinggroup'),
        ),
    ]
