# Generated by Django 3.2.16 on 2023-01-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0013_alter_groupmembership_meeting_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="votes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Vote weight delegated"
            ),
        ),
    ]
