# Generated by Django 3.2.16 on 2023-02-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_auto_20230112_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'verbose_name': 'Group membership', 'verbose_name_plural': 'Group memberships'},
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('user', 'meeting_group'), name='unique_user_in_meeting_group'),
        ),
    ]
