# Generated by Django 3.2.18 on 2023-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0016_alter_groupmembership_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting",
            old_name="installed_dialects",
            new_name="installed_dialect",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="installed_dialect",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Configuration steps for roles, groups or similar + possible restrictions.",
            ),
        ),
    ]
