# Generated by Django 3.2.18 on 2023-04-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0017_auto_20230323_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDialectProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('meeting.meeting',),
        ),
    ]
