# Generated by Django 3.2.18 on 2023-04-27 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0018_meetingdialectproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinggroup',
            name='delegate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='delegations_from', to='meeting.meetinggroup'),
        ),
        migrations.AddConstraint(
            model_name='meetinggroup',
            constraint=models.CheckConstraint(check=models.Q(('pk', django.db.models.expressions.F('delegate_to_id')), _negated=True), name='prevent_delegate_to_self'),
        ),
    ]
