# Generated by Django 3.2.22 on 2023-11-02 14:35

from django.db import migrations
import voteit.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0020_meetingroles_migration_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprole',
            name='roles',
            field=voteit.core.fields.RolesField(choices=[('di', 'Discusser'), ('mo', 'Moderator'), ('pa', 'Participant'), ('pv', 'Potential voter'), ('pr', 'Proposer')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='meetingroles',
            name='assigned',
            field=voteit.core.fields.RolesField(choices=[('di', 'Discusser'), ('mo', 'Moderator'), ('pa', 'Participant'), ('pv', 'Potential voter'), ('pr', 'Proposer')], default='', max_length=60),
        ),
    ]
