# Generated by Django 3.2.22 on 2024-02-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0021_auto_20231102_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprole',
            name='can_discuss_as',
        ),
        migrations.RemoveField(
            model_name='grouprole',
            name='can_propose_as',
        ),
    ]
