# Generated by Django 3.2.22 on 2024-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0022_auto_20240219_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinggroup',
            name='post_as',
            field=models.BooleanField(default=False, verbose_name='Allow members to post as group'),
        ),
        migrations.AddField(
            model_name='meetinggroup',
            name='post_with',
            field=models.BooleanField(default=True, verbose_name='Allow members to display group next to name when posting'),
        ),
        migrations.AddField(
            model_name='meetinggroup',
            name='show_on_speaker',
            field=models.BooleanField(default=True, verbose_name='Display group name on speaker entry in speaker lists'),
        ),
    ]
