# Generated by Django 3.2.22 on 2024-02-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0023_auto_20240222_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinggroup',
            name='post_with',
        ),
    ]
