# Generated by Django 4.2.15 on 2024-11-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meeting",
            "0025_alter_meeting_author_alter_meeting_last_modified_by_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="meetinggroup",
            name="prevent_delegate_to_self",
        ),
        migrations.AddConstraint(
            model_name="meetinggroup",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("delegate_to_id__isnull", True),
                    models.Q(("pk", models.F("delegate_to_id")), _negated=True),
                    _connector="OR",
                ),
                name="prevent_delegate_to_self",
            ),
        ),
    ]
