# Generated by Django 5.2.3 on 2025-09-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0026_remove_meetinggroup_prevent_delegate_to_self_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MeetingDialectProxy",
        ),
    ]
