# Generated by Django 5.2.13 on 2026-05-08 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0027_delete_meetingdialectproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meeting.grouprole'),
        ),
    ]
