# Generated by Django 5.2.13 on 2026-05-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0028_alter_groupmembership_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='meetinggroup',
            name='last_modified_by',
        ),
    ]
