# Generated by Django 5.2.14 on 2026-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0029_remove_meeting_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='state',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('archiving', 'Archiving'), ('archived', 'Archived'), ('deleting', 'Deleting')], default='upcoming', max_length=20),
        ),
    ]
