# Generated by Django 5.2.15 on 2026-08-19 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('channel_name', models.CharField(max_length=150)),
                ('connected_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_action', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('code', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-last_action',),
            },
        ),
    ]
