# Generated by Django 5.2.15 on 2026-08-19 11:59

"""Indexes for the Connection query shapes.

Measured on a 863k-row copy of the dev database, the "currently online"
lookup (code IS NULL AND last_action > cutoff) went from a 38.5ms parallel
sequential scan to a 0.125ms index scan. The table is never reaped, so it
only grows.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteit_messaging', '0002_import_envelope_connections'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['user_id'], name='conn_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['last_action'], name='conn_last_action_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(condition=models.Q(('code__isnull', True)), fields=['last_action'], name='conn_open_last_action_idx'),
        ),
    ]
