# Generated by Django 3.2.7 on 2022-02-08 13:25

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0002_auto_20220126_1115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=tuple, max_length=20), size=None)),
                ('user_platform', django.contrib.postgres.fields.jsonb.JSONField()),
                ('function', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('state', django_fsm.FSMField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='unresolved', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bug report',
                'verbose_name_plural': 'Bug reports',
                'ordering': ('-created',),
            },
        ),
    ]
