# Generated by Django 5.2.13 on 2026-04-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reports', '0002_alter_bugreport_user_platform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugReport',
        ),
    ]
