# Generated by Django 5.2.14 on 2026-05-28 10:11

import voteit.token_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingapikey',
            name='scopes',
            field=models.JSONField(blank=True, default=list, validators=[voteit.token_api.validators.validate_api_key_scopes]),
        ),
    ]
