# Generated by Django 5.2.11 on 2026-02-04 14:36

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0013_remove_oauth2provider_provider_id_delete_accesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_online_count', models.IntegerField(default=0, verbose_name='Unique users online')),
                ('connection_count', models.IntegerField(default=0, verbose_name='Socket connections made')),
                ('action_count', models.IntegerField(default=0, verbose_name='Logged action count')),
                ('action_types', models.JSONField(default=dict, verbose_name='Actions on different content types')),
                ('content_types', models.JSONField(default=dict, verbose_name='Total count of different content types')),
                ('online_duration', models.DurationField(default=datetime.timedelta, verbose_name='Total time online')),
                ('mean_online_duration', models.GeneratedField(db_persist=True, expression=models.Case(models.When(then=datetime.timedelta(0), user_online_count=0), default=models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('online_duration'), '/', models.F('user_online_count')), output_field=models.DurationField())), output_field=models.DurationField(), verbose_name='Mean time online')),
                ('accepted_invitation_count', models.IntegerField(default=0, verbose_name='Accepted invitations')),
                ('login_count', models.IntegerField(default=0, verbose_name='User login count')),
                ('spoken_duration', models.DurationField(default=datetime.timedelta, verbose_name='Total time spoken')),
                ('speaker_count', models.IntegerField(default=0, verbose_name='Unique speaker count')),
                ('mean_spoken_duration', models.GeneratedField(db_persist=True, expression=models.Case(models.When(speaker_count=0, then=datetime.timedelta(0)), default=models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('spoken_duration'), '/', models.F('speaker_count')), output_field=models.DurationField())), output_field=models.DurationField(), verbose_name='Mean time spoken')),
                ('proposal_outcomes', models.JSONField(default=dict, verbose_name='Proposal outcomes')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation')),
            ],
            options={
                'verbose_name': 'History Log',
                'verbose_name_plural': 'History Logs',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('org', 'date'), name='unique_org_date')],
            },
        ),
    ]
