# Generated by Django 3.2.7 on 2021-10-22 12:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import voteit.reactions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Display name')),
                ('icon', models.CharField(choices=[('mdi-thumb-up', 'Thumb up'), ('mdi-thumb-down', 'Thumb down'), ('mdi-check', 'Checkmark'), ('mdi-cancel', 'Block'), ('mdi-star', 'Star'), ('mdi-wheelchair-accessibility', 'Accessible'), ('mdi-heart', 'Heart'), ('mdi-forum', 'Forum'), ('mdi-alert', 'Alert'), ('mdi-attachment', 'Attachment'), ('mdi-pencil', 'Pencil'), ('mdi-currency-eur', 'Currency')], max_length=80, verbose_name='Icon name')),
                ('color', models.CharField(choices=[('accent', 'Accent'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('error', 'Error'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning')], max_length=80, verbose_name='Color')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('change_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=tuple, size=None)),
                ('list_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=tuple, size=None)),
                ('active', models.BooleanField(default=True, verbose_name='Is this activated?')),
                ('allowed_models', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=voteit.reactions.models._default_allowed_models, size=None)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_buttons', to='meeting.meeting')),
            ],
            options={
                'verbose_name': 'Reaction button',
                'verbose_name_plural': 'Reaction buttons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='agenda.agendaitem')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='reactions.reactionbutton')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'unique_together': {('content_type', 'object_id', 'button', 'user')},
            },
        ),
    ]
