# Generated by Django 3.2.6 on 2022-01-23 11:42

import django.contrib.postgres.fields
from django.db import migrations, models
import voteit.reactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionbutton',
            name='allowed_models',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=voteit.reactions.models._default_allowed_models, size=None),
        ),
    ]
