# Generated by Django 3.2.13 on 2022-04-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_alter_reactionbutton_allowed_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reactionbutton',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
