# Generated by Django 3.2.16 on 2022-11-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_auto_20220418_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionbutton',
            name='target',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Required target'),
        ),
        migrations.AlterField(
            model_name='reactionbutton',
            name='color',
            field=models.CharField(max_length=15, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='reactionbutton',
            name='icon',
            field=models.CharField(max_length=30, verbose_name='Icon name'),
        ),
    ]
