# Generated by Django 3.2.19 on 2023-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0005_alter_reaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionbutton',
            name='flag_mode',
            field=models.BooleanField(default=False, verbose_name='Flag mode?'),
        ),
        migrations.AddField(
            model_name='reactionbutton',
            name='on_presentation',
            field=models.BooleanField(default=False, verbose_name='Show in presentation mode'),
        ),
        migrations.AddField(
            model_name='reactionbutton',
            name='on_vote',
            field=models.BooleanField(default=False, verbose_name='Show during vote'),
        ),
    ]
