# Generated by Django 3.2.19 on 2023-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0006_auto_20230926_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionbutton',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='reactionbutton',
            name='vote_template',
            field=models.BooleanField(default=False, verbose_name='As Vote template'),
        ),
        migrations.AlterField(
            model_name='reactionbutton',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Icon name'),
        ),
    ]
