# Generated by Django 3.2.22 on 2023-11-01 13:25

from django.db import migrations
import voteit.core.fields

_MODEL = ("reactions", "ReactionButton")


def migrate_role(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        roles.m_change_roles = roles.change_roles
        roles.m_list_roles = roles.list_roles
        roles.save()


def reverse_migrate_role(apps, schema_editor):
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        roles.change_roles = roles.m_change_roles
        roles.list_roles = roles.m_list_roles
        roles.save()


class Migration(migrations.Migration):
    dependencies = [
        ("reactions", "0007_auto_20231003_1127"),
    ]

    operations = [
        migrations.AddField(
            model_name="reactionbutton",
            name="m_change_roles",
            field=voteit.core.fields.RolesField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="reactionbutton",
            name="m_list_roles",
            field=voteit.core.fields.RolesField(default="", max_length=60),
        ),
        migrations.RunPython(code=migrate_role, reverse_code=reverse_migrate_role),
        migrations.RemoveField(
            model_name="reactionbutton",
            name="change_roles",
        ),
        migrations.RemoveField(
            model_name="reactionbutton",
            name="list_roles",
        ),
        migrations.RenameField(
            model_name="reactionbutton",
            old_name="m_change_roles",
            new_name="change_roles",
        ),
        migrations.RenameField(
            model_name="reactionbutton",
            old_name="m_list_roles",
            new_name="list_roles",
        ),
    ]
