# Generated by Django 3.2.22 on 2023-11-02 14:35

from django.db import migrations
import voteit.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0008_auto_20231101_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionbutton',
            name='change_roles',
            field=voteit.core.fields.RolesField(choices=[('di', 'Discusser'), ('mo', 'Moderator'), ('pa', 'Participant'), ('pv', 'Potential voter'), ('pr', 'Proposer')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='reactionbutton',
            name='list_roles',
            field=voteit.core.fields.RolesField(choices=[('di', 'Discusser'), ('mo', 'Moderator'), ('pa', 'Participant'), ('pv', 'Potential voter'), ('pr', 'Proposer')], default='', max_length=60),
        ),
    ]
