# Generated by Django 5.2.3 on 2025-09-04 12:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0027_delete_meetingdialectproxy"),
        ("reactions", "0009_auto_20231102_1535"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reactionbutton",
            constraint=models.UniqueConstraint(
                models.F("meeting"),
                django.db.models.functions.text.Lower("title"),
                django.db.models.functions.text.Lower("icon"),
                django.db.models.functions.text.Lower("color"),
                name="unique_buttons_per_meeting",
            ),
        ),
    ]
