# Generated by Django 3.2.16 on 2023-03-09 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invites', '0003_auto_20220418_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginvite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetinginvite',
            name='last_modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
