# Generated by Django 3.2.18 on 2023-04-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0004_auto_20230309_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinginvite',
            name='last_sent',
        ),
        migrations.RemoveField(
            model_name='meetinginvite',
            name='send_state',
        ),
        migrations.DeleteModel(
            name='InviteDispatch',
        ),
    ]
