# Generated by Django 3.2.18 on 2023-04-04 08:38

import django.core.serializers.json
from django.db import migrations, models


def move_invite_data(apps, *args):
    MeetingInvite = apps.get_model("invites", "meetinginvite")
    for obj in MeetingInvite.objects.all():
        if obj.type == "email":
            obj.user_data = {"email": [obj.invite_data]}
        elif obj.type == "swedish_ssn":
            obj.user_data = {"swedish_ssn": obj.invite_data}
        else:
            raise ValueError(f"{obj} contained value {obj.type} as type")
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0005_auto_20230403_1659"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetinginvite",
            name="user_data",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(move_invite_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="meetinginvite",
            name="invite_data",
        ),
        migrations.RemoveField(
            model_name="meetinginvite",
            name="type",
        ),
    ]
