# Generated by Django 3.2.18 on 2023-04-22 15:24

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ("meeting", "0018_meetingdialectproxy"),???
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invites", "0005_auto_20230403_1659"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetinginvite",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meetinginvite",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meetinginvite",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="used_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
