# Generated by Django 3.2.18 on 2023-04-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0006_auto_20230404_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinginvite',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meetinginvite',
            name='last_modified_by',
        ),
    ]
