# Generated by Django 3.2.18 on 2023-04-22 15:30

import django.core.serializers.json
from django.db import IntegrityError
from django.db import migrations, models
import django.db.models.deletion


def move_invite_data(apps, *args):
    MeetingInvite = apps.get_model("invites", "meetinginvite")
    for obj in MeetingInvite.objects.all():
        if obj.type == "email":
            obj.user_data = {"email": obj.invite_data}
        elif obj.type == "swedish_ssn":
            obj.user_data = {"swedish_ssn": obj.invite_data}
        else:
            raise ValueError(f"{obj} contained value {obj.type} as type")
        obj.save_base(raw=True)


def reverse_move_invite_data(apps, *args):
    MeetingInvite = apps.get_model("invites", "meetinginvite")
    for obj in MeetingInvite.objects.all():
        if len(obj.user_data) > 2:
            raise IntegrityError(
                "Migration can't reverse since there were userdata with multiple keys"
            )
        for (k, v) in obj.user_data.items():
            obj.type = k
            obj.invite_data = v
            obj.save_base(raw=True)


class Migration(migrations.Migration):

    dependencies = [
        # ("meeting", "0018_meetingdialectproxy"),  # Eh?
        ("invites", "0006_auto_20230422_1724"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetinginvite",
            name="user_data",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
            preserve_default=False,
        ),
        migrations.RunPython(move_invite_data, reverse_code=reverse_move_invite_data),
        migrations.RemoveField(
            model_name="meetinginvite",
            name="invite_data",
        ),
        migrations.RemoveField(
            model_name="meetinginvite",
            name="type",
        ),
    ]
