# Generated by Django 3.2.18 on 2023-04-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0018_meetingdialectproxy"),
        ("invites", "0007_auto_20230417_1513"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingGroupAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="meeting.grouprole",
                    ),
                ),
                (
                    "meeting_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="meeting.meetinggroup",
                    ),
                ),
                (
                    "meeting_invite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_annotations",
                        to="invites.meetinginvite",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="meetinggroupannotation",
            constraint=models.UniqueConstraint(
                fields=("meeting_group", "meeting_invite"),
                name="unique_invite_group_annotation",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetinginvite",
            constraint=models.UniqueConstraint(
                fields=("meeting", "user_data"), name="unique_meeting_invite_user_data"
            ),
        ),
    ]
