# Generated by Django 3.2.18 on 2023-04-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0007_auto_20230422_1730"),
    ]

    operations = [
        # Blanked this migration so constraint end up last
    ]
