# Generated by Django 3.2.18 on 2023-04-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0018_meetingdialectproxy'),
        ('invites', '0008_auto_20230419_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinggroupannotation',
            name='group_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meeting.grouprole'),
        ),
        migrations.AlterField(
            model_name='meetinggroupannotation',
            name='meeting_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_annotations', to='meeting.meetinggroup'),
        ),
    ]
