# Generated by Django 3.2.18 on 2023-04-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0008_auto_20230422_1734"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingGroupAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="meeting.grouprole",
                    ),
                ),
                (
                    "meeting_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_annotations",
                        to="meeting.meetinggroup",
                    ),
                ),
                (
                    "meeting_invite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_annotations",
                        to="invites.meetinginvite",
                    ),
                ),
            ],
        ),
    ]
