# Generated by Django 3.2.18 on 2023-04-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0009_auto_20230422_1736"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meetinggroupannotation",
            constraint=models.UniqueConstraint(
                fields=("meeting_group", "meeting_invite"),
                name="unique_invite_group_annotation",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetinginvite",
            constraint=models.UniqueConstraint(
                fields=("meeting", "user_data"), name="unique_meeting_invite_user_data"
            ),
        ),
    ]
