# Generated by Django 3.2.22 on 2023-11-01 08:25

from django.db import migrations
import voteit.core.fields

_ROLE_LETTER_MIGRATION = (
    ("p", "participant"),
    ("m", "moderator"),
    ("v", "potential_voter"),
    ("d", "discusser"),
    ("r", "proposer"),
)

_MODEL = ("invites", "MeetingInvite")


def migrate_role(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        # v = ""
        # for letter, name in _ROLE_LETTER_MIGRATION:
        #    if name in roles.assigned:
        #        v += letter
        # roles.migration_assigned = v
        roles.migration_roles = roles.roles
        roles.save()


def reverse_migrate_role(apps, schema_editor):
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        # v = []
        # for letter, name in _ROLE_LETTER_MIGRATION:
        #     if letter in roles.migration_assigned:
        #         v.append(name)
        # roles.assigned = v
        roles.roles = roles.migration_roles
        roles.save()


class Migration(migrations.Migration):
    dependencies = [
        ("invites", "0010_auto_20230425_2044"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetinginvite",
            name="migration_roles",
            field=voteit.core.fields.RolesField(default="", max_length=60),
        ),
        migrations.RunPython(
            code=migrate_role,
            reverse_code=reverse_migrate_role,
        ),
        migrations.RemoveField(
            model_name="meetinginvite",
            name="roles",
        ),
        migrations.RenameField(
            model_name="meetinginvite",
            new_name="roles",
            old_name="migration_roles",
        ),
    ]
