# Generated by Django 3.2.22 on 2023-11-01 08:25

from django.db import migrations
import voteit.core.fields

_SHORTER_ROLE_NAME_MAP = {
    "participant": "pa",
    "moderator": "mo",
    "potential_voter": "pv",
    "discusser": "di",
    "proposer": "pr",
}

_MODEL = ("invites", "MeetingInvite")


def migrate_role(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    for roles in model.objects.using(db_alias).all():
        values = []
        for v in roles.roles:
            values.append(_SHORTER_ROLE_NAME_MAP[v])
        roles.migration_roles = values
        model.save_base(roles, raw=True)


def reverse_migrate_role(apps, schema_editor):
    model = apps.get_model(*_MODEL)
    db_alias = schema_editor.connection.alias
    reversed_map = {v: k for k, v in _SHORTER_ROLE_NAME_MAP.items()}
    for roles in model.objects.using(db_alias).all():
        values = []
        for v in roles.migration_roles:
            values.append(reversed_map[v])
        roles.roles = values
        model.save_base(roles, raw=True)


class Migration(migrations.Migration):
    dependencies = [
        ("invites", "0010_auto_20230425_2044"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetinginvite",
            name="migration_roles",
            field=voteit.core.fields.RolesField(default="", max_length=60),
        ),
        migrations.RunPython(
            code=migrate_role,
            reverse_code=reverse_migrate_role,
        ),
        migrations.RemoveField(
            model_name="meetinginvite",
            name="roles",
        ),
        migrations.RenameField(
            model_name="meetinginvite",
            new_name="roles",
            old_name="migration_roles",
        ),
    ]
