# Generated by Django 3.2.22 on 2023-11-02 14:35

from django.db import migrations
import voteit.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0011_meetinginvite_migration_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginvite',
            name='roles',
            field=voteit.core.fields.RolesField(choices=[('di', 'Discusser'), ('mo', 'Moderator'), ('pa', 'Participant'), ('pv', 'Potential voter'), ('pr', 'Proposer')], default='', max_length=60),
        ),
    ]
