# Generated by Django 5.2.7 on 2025-10-27 20:31

import django.core.serializers.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0012_alter_meetinginvite_roles'),
        ('meeting', '0027_delete_meetingdialectproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meetinginvite',
            name='unique_meeting_invite_user_data',
        ),
        migrations.RemoveField(
            model_name='meetinginvite',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meetinginvite',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='meetinginvite',
            name='user_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddConstraint(
            model_name='meetinginvite',
            constraint=models.UniqueConstraint(condition=models.Q(('user_data__exact', {}), _negated=True), fields=('meeting', 'user_data'), name='unique_meeting_invite_user_data'),
        ),
    ]
