# Generated by Django 5.2.14 on 2026-06-02 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0013_remove_meetinginvite_unique_meeting_invite_user_data_and_more'),
        ('meeting', '0029_remove_meeting_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinggroupannotation',
            name='group_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meeting.grouprole'),
        ),
    ]
