# Generated by Django 5.2.14 on 2026-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0014_alter_meetinggroupannotation_group_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginvite',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='open'),
        ),
    ]
