name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ['3.12']

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      memcached:
        image: memcached
        ports:
          - "11211:11211"
    steps:
    - uses: actions/checkout@v3

    - name: Checkout / voteit_org
      uses: actions/checkout@v6
      with:
        repository: voteit/voteit_org
        path: src/voteit_org

    - name: Checkout / member_dialects
      uses: actions/checkout@v6
      with:
        repository: voteit/member_dialects
        path: src/member_dialects

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        #cache: 'pip' <- Requires requirements.txt to be specified and NOT contain this package!!!

    - name: Install dependencies
      run: |
        uv sync

    - name: Django testrunner
      run: |
        uv run ./manage.py test voteit
      env:
        DJANGO_DEBUG: 1
        DJANGO_SETTINGS_MODULE: project.settings
        POSTGRES_HOST: 127.0.0.1
        ID_HOST: https://id.voteit.se
        OAUTHLIB_INSECURE_TRANSPORT: 1
        HOST: .voteit.se
        MEMCACHE_LOCATION: 127.0.0.1:11211
